# CSS 342
# This file is for GitHub grading

# DO NOT CHANGE IN FINAL SUBMISSION

name: css 342 grader

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #  types: [ opened, reopened, synchronize ]
#  schedule:
#    - cron: "* * * */1 *"

jobs:
  CSS342_Grader_Bot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grader bot Nop the cat greets
        run: cat .github/workflows/graderbot.art
      - name: Verify no changes to the grader scripts
        run: bash .github/workflows/check_no_change_to_grader.sh
      - name: Install packages
        run: .github/workflows/install_dependencies.sh
      - name: Create Makefile
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_COV=true .
      - name: Build code
        run: make -j4
      - name: Run unit tests
        run: make function_tests # run all executables ending with "_test"
      - name: Run memory tests
        run: .github/workflows/memcheck.sh
      - name: Cheer!
        run: bash .github/workflows/success.sh
